openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://127.0.0.1:8080
    description: Optional server description, e.g. Main (production) server
  - url: http://127.0.0.1:8080
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: auth
    description: Authentication login and sign up
    externalDocs:
      description: Find out more
      url: https://swagger.io
paths:
  /login:
    post:
      summary: Login account
      description: Login account
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email
                password:
                  type: string
                  description: Password
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Access token
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message explaining the reason for the unauthorized status.
  /signup:
    post:
      summary: Sign up for a new account
      description: Create a new user account
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email address for the new account
                password:
                  type: string
                  description: Password for the new account
                fullName:
                  type: string
                  description: Full name of the user
      responses:
        "201":
          description: Account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
                  userId:
                    type: string
                    description: Unique identifier for the newly created user
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message explaining the reason for the bad request.
